### ISSUE TITLE
Player 1 death triggers the rest of camera offsets to be set to player 3

### ISSUE THREAD

**Issue by Ashen-Vaults** [drexelseniorproject/sproj#1]
<img width="715" alt="bug1" src="https://cloud.githubusercontent.com/assets/13257699/9776467/88deebca-5726-11e5-8475-acd579260125.PNG">

**Comment by megadook** [comment]
fixed, the allInstances list on the InstanceManager was not being updated after a death, leaving that and the allScreens list to be no longer parallel
