### ISSUE TITLE
Lose Routine is giving issues when player 1 or 3 "win" Camera offsets being displaced.

### ISSUE THREAD

**Issue by Ashen-Vaults** [drexelseniorproject/sproj#3]
<img width="687" alt="bug 1 3" src="https://cloud.githubusercontent.com/assets/13257699/9776551/8fe20122-5727-11e5-884a-dddfd1726e14.PNG">

**Comment by Ashen-Vaults** [comment]
Not workingtesting

**Comment by Ashen-Vaults** [comment]
<img width="1055" alt="capture" src="https://cloud.githubusercontent.com/assets/13257699/9778140/9f066bd0-573a-11e5-8cb5-4404c4dc5d9d.PNG">

**Comment by megadook** [comment]
fixed, see other issue for explaination
